/** change_log.field → 화면 라벨. 인사카드 변경 기록과 전체 변경이력 페이지가 함께 쓴다 */
export const FIELD_LABEL: Record<string, string> = {
  name_ko: "한글성명",
  name_en: "영문성명",
  company: "소속",
  department: "부서명",
  position: "직급",
  status: "재직구분",
  birth_date: "생년월일",
  hire_date: "입사일",
  resign_date: "퇴사일",
  email: "메일계정",
  phone: "휴대전화",
  hire_type: "채용구분",
  employment_type: "고용형태",
  residence: "거주지역",
  effective_date: "발령일자",
  contract_end_date: "계약종료일",
  return_date: "복직예정일",
  emergency_contact: "비상연락망",
  photo_url: "사진",
  "신규 등록": "신규 등록",
};
